name: whisper-dynamic-training
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python>=3.8
  - pip>=21.0

  # Core ML/DL Libraries
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - cudatoolkit=11.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  
  # Audio Processing
  - librosa>=0.9.0
  - pysoundfile>=0.10.3
  - scipy>=1.7.0
  
  # Progress Tracking
  - tqdm>=4.65.0

  # Redis
  - redis-py>=4.5.0

  # Pip packages (for packages not available in conda)
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - evaluate>=0.4.0
    - pyrubberband>=0.3.0
    - pyplnoise>=0.1.0
    - bnunicodenormalizer>=0.0.40
    - soundfile>=0.10.3
    # Optional: Uncomment if using MLflow
    # - mlflow>=2.3.0

variables:
  # Optional: Set environment variables
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512" 